// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic';

export const components = {
  full_width_image: dynamic(() => import('./FullWidthImage')),
  image_one: dynamic(() => import('./ImageOne')),
  size: dynamic(() => import('./Size')),
  two_images: dynamic(() => import('./TwoImages')),
  video: dynamic(() => import('./Video')),
};
